HTML and CSS Project 2: HTML Forms
ricardomonte/HTML_Forms pull request #1
Opened 2020-08-15 22:24 UTC by ricardomonte

In this project:

- We structure the html using:

> Semantic

> Normalizer

> CSS stylesheet

- We also create the style using:

> CSS Flexbox

> CSS Grid

2020-08-15 23:13 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

 
### Hi team, you guys did a very good job so far! 💪
Amazing use of semantic HTML5, code looks also very clean and professional. 👏👌


#### I know you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

[REQUIRED CHANGES]
- [x] Check usage of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) from Pathwright)
- [x] Remove all the unnecessary repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))
- [x] Add your CSS files to a style or css folder. (It will make your repo look more professional)

[OPTIONAL CHANGES]
- [x] Make your Readme file look more professional by working on its layout (add emojis and so on)

### Tips:

* In your CSS file, there's a lot of repeated rules. e.g.: Instead of having 6x `width: 100%;`, create a single class: `.width-100 { 
width: 100% 
}`   and apply it in your HTML file.
![image](https://user-images.githubusercontent.com/56762529/90323019-d64d4080-df31-11ea-81f4-ed21c00a825a.png)




**Please make the required changes and resubmit for a new code review once you are ready**

 

As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

 

 

📫 Have any question? Better call Kevin:

 

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-15 23:13 UTC, kevincappuccino commented on index.html
> +              <div class="label-password lbl-position" tabindex="0">
Remember to use [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp). You guys forgot to use the correct tag here. Kindly fix that.

2020-08-17 17:14 UTC, SpaYco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] The [HTML Validator](https://validator.w3.org/#validate_by_upload) shows an error 
![image](https://user-images.githubusercontent.com/11758151/90423485-716e2380-e0b4-11ea-867b-7a6067ae0a91.png)

## Optional 

- [x] your form is not well centered, please fix that

- [x] change your page's title


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-17 21:02 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello @ricardomonte and @kcotrinam92 :wave: 

## You did an amazing job by making all of the required changes! Congratulations, your project is approved :clap: :clap: :clap: 

## You may merge to the master branch. Good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-17 21:10 UTC, merged